version: '3.8'

services:
  flask-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development
    working_dir: /02_CRUD_Strategy
    command: ["flask", "run"]

  mongodb-server:
    image: mongo
    container_name: mongodb-server
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
